export const morningQuotes = [
  "Wake up and conquer. The office can't break your discipline today.",
  "Start strong. The energy you build now carries into the gym tonight.",
  "Your 9-to-5 is your job. Your health is your life. Prioritize correctly.",
  "Outwork everyone in the board room, outwork them on the squat rack.",
  "Discipline starts the moment your feet hit the floor at 9 AM.",
  "Hydrate heavily. Your body needs fuel for the stress of the day.",
  "Another day, another opportunity to prove your excuses wrong.",
  "Success is leased, and rent is due every single morning.",
  "Don't let desktop posture ruin your gains. Stay sharp today.",
  "You hold the pen to the story of today. Write a masterpiece.",
  "Let your work ethic echo out from the office and into the iron.",
  "A productive morning guarantees a powerful evening lift.",
  "Seize the hours. Build your career without sacrificing your physique.",
  "Focus on the task at hand. Keep your gym goals alive in the background.",
  "Stay hydrated, stay focused. The countdown to 6 PM starts now.",
  "It's just another day to out-hustle yesterday's version of you.",
  "Office stress is temporary. Iron discipline is permanent.",
  "Don't hit snooze on your life. Grab your coffee and attack the day.",
  "Mental strength developed at work translates directly to physical power.",
  "Your dedication to excellence doesn't stop when you log in.",
  "Be relentless in your career, be ruthless in your training.",
  "Use the morning to sharpen your mind; use the evening to sharpen the body.",
  "Step into the office with the same intensity you step into the gym.",
  "Drink water. Move your body. Your desk won't define you today.",
  "Every hour is an investment in your ultimate goal.",
  "Bring the heat today. Nobody cares about excuses.",
  "The grit you show tackling emails is the grit you need moving weights.",
  "Conquer the morning meetings. Protect your energy for the evening iron.",
  "Make every minute count today. Your results rely on 100% consistency.",
  "The grind doesn't care if you're tired. Show up and do the work.",
  "Excel today so you have zero regrets hitting the gym at 6 PM.",
  "Your mind is a muscle. Train it during office hours.",
  "The difference between who you are and who you want to be is what you do.",
  "Attack the morning. Make the day respect you.",
  "Don't let the corporate grind break your physical drive.",
  "Keep your vision clear. Career growth alongside physical growth.",
  "Hydrate, focus, execute. The holy trinity of a productive morning.",
  "You're not just working a job, you're building an empire.",
  "The hardest part of the day is starting. You're already ahead.",
  "Let nothing distract you from dominating today's targets.",
  "Turn office anxiety into workout fuel for later.",
  "Your body is a machine. Fuel it right while sitting at the desk.",
  "Step out the door with purpose. You're a warrior in business attire.",
  "Do not compromise your nutrition today. Prepare for war tonight.",
  "Discipline is a lifestyle, applied to spreadsheets and deadlifts alike.",
  "Keep moving forward. 9 AM is the starting pistol.",
  "Your mindset dictates your reality. Choose greatness today.",
  "Stay vigilant. Hydrate consistently. Protect your gains from the desk.",
  "Make the morning yours, or the morning will make you.",
  "You've survived 100% of your bad days. Time to create a great one."
];

export const preWorkoutQuotes = [
  "6 PM. Clock out of work. Clock in to the iron.",
  "Leave the office stress at the door. The barbell is your therapist.",
  "No more emails. Time to pick up heavy things.",
  "You're tired from work? Good. Let the iron wake you up.",
  "Switch gears. You are no longer an employee; you are an athlete.",
  "The real workday starts now. Destroy those excuses.",
  "Pack your bag, change your mindset. The gym is waiting.",
  "Nobody cares about how long your commute was. Just lift.",
  "Your competition is already warming up. Don't lag behind.",
  "This is where the separation happens. 6 PM is the proving ground.",
  "It's easy to go home and watch TV. That's why average does it.",
  "Take off the tie, put on the lifting belt. Time for war.",
  "You promised yourself you'd go. Honor your own word.",
  "The weights don't care about your bad day at work.",
  "Fuel up. Get loud. Hit the PR.",
  "Your office job pays the bills. Your gym session pays your soul.",
  "Transition complete. Unleash the beast.",
  "Don't let the couch seduce you. The squat rack is calling.",
  "6 PM: The universal hour for grinding out greatness.",
  "You have 30 minutes to get your head right. Focus.",
  "Every rep tonight erases a worry from the office today.",
  "Be stronger than your strongest excuse.",
  "Your future self is thanking you for not driving straight home.",
  "Clock out, tune out the world, tune into the iron.",
  "Sweat solves 90% of the problems you faced today.",
  "Hit the gym. Earn your dinner. Earn your rest.",
  "There is no 'skip' button on the road to success.",
  "Let out the corporate frustration on the weights.",
  "The iron is unconditionally loyal. Treat it with respect tonight.",
  "This is your hour. Reclaim your body from the desk chair.",
  "Put the pre-workout in. It's time to build the machine.",
  "Work was just a warm-up. This is the main event.",
  "Nothing feels better than a finished workout. Go earn that feeling.",
  "You didn't survive the workday just to skip the gym.",
  "Change your clothes, change your destiny.",
  "Drive past the house. Head straight to the temple.",
  "It's you against you. The workday is over. Prove it.",
  "The only bad workout is the one that didn't happen.",
  "Let the adrenaline replace the caffeine. Hit it hard.",
  "The office demands your brain. The gym demands everything else.",
  "You've got 60 minutes to make a 1% improvement. Go.",
  "Your commute home is just the pathway to your personal growth.",
  "Don't negotiate with weakness. The gym was the plan.",
  "Show up for yourself the way you show up for your boss.",
  "There is no perfect time. There is only now. 6 PM. Go.",
  "Commitment means staying loyal to what you said you were going to do.",
  "Embrace the exhaustion. It means you're changing.",
  "Get in the zone. You have demons to exorcise.",
  "Your body is craving movement. Give it a challenge.",
  "Turn the volume up. Tune the world out. Let's work."
];

export const eveningQuotes = [
  "11 PM. The workday is done, the gym is conquered. Rest easy.",
  "Sleep is the ultimate super-supplement. Don't skip it.",
  "Your muscles grow when you rest. Close your eyes and recover.",
  "Review your wins today. You outworked the excuses.",
  "Tomorrow's goals are decided tonight. Prepare your gym bag.",
  "Hydrate before bed. Let your body heal the damage you did today.",
  "You cannot perform at 100% tomorrow with only 50% sleep tonight.",
  "The screen is stealing your gains. Turn it off. Go to sleep.",
  "A disciplined morning requires a disciplined bedtime.",
  "Growth happens in the silence of the night.",
  "Reflect on your discipline. You chose the hard path today. Be proud.",
  "Rest well, warrior. Another battle awaits at 9 AM.",
  "Your nutrition is prepped. Your alarm is set. Power down.",
  "Sleep is a weapon. Arm yourself for tomorrow.",
  "The hardest workout is worthless without recovery. Time for bed.",
  "Forgive yourself for today's mistakes. Attack them tomorrow.",
  "You pushed your limits today. Allow your body to rebuild.",
  "Disconnect from the noise. Your mind needs silence to stay sharp.",
  "Respect the circadian rhythm. Your physique depends on it.",
  "Every hour of sleep is a deposit into tomorrow's energy bank.",
  "If you want to be exceptional tomorrow, sleep like it tonight.",
  "Your daily streak is intact. Celebrate the small victories.",
  "Prepare the coffee machine. Layout the clothes. Ensure seamless execution.",
  "Worrying about tomorrow robs tonight of its peace. Rest.",
  "Healing occurs in deep sleep. Go find it.",
  "You've earned this rest. You fought hard in the office and the gym.",
  "Don't sabotage your morning by scrolling right now. Turn off the phone.",
  "Embrace the fatigue. It's the physical proof of your ambition.",
  "Discipline means going to bed when you know you should.",
  "You are one sleep cycle away from a brand new opportunity.",
  "Nighttime is for recovery, not overthinking. Unplug.",
  "Tomorrow requires a rested mind to dominate the office.",
  "A quiet mind guarantees a powerful tomorrow.",
  "The blueprint is laid. Let the body construct the changes.",
  "Reflect. Recharge. Restart.",
  "Good sleep is the foundation of peak productivity.",
  "You're building an elite routine. Stick to the bedtime.",
  "No more screens. Only recovery.",
  "Let the satisfaction of a productive day guide you to sleep.",
  "You held the line today. Stand tall, rest well.",
  "A true champion respects their recovery phase.",
  "The body is a battery. Plug it in by going to sleep.",
  "Breathe deep, let the office stress dissolve into the night.",
  "You can't pour from an empty cup. Refill it tonight.",
  "Shut out the world. The shift is over.",
  "Your goals don't care about how tired you are. Get the right sleep.",
  "Tomorrow's success begins with the discipline of tonight.",
  "Hydrate, breathe, log off. You survived another one.",
  "The weights will be there tomorrow. Go to bed.",
  "You are exactly where you need to be. Goodnight."
];
